openapi: 3.2.0
info:
  description: API for Synadia Control Plane / Synadia Cloud
  title: Synadia Control Plane / Synadia Cloud App Service Account…
  version: beta
servers:
- description: Path to Synadia Control Plane Server Api
  url: '{baseUrl}/api'
  variables:
    baseUrl:
      default: ''
security:
- bearerAuth: []
  sessionAuth: []
tags:
- name: app-service-account-tokens
paths:
  /core/beta/service-account-tokens/app/{tokenId}:
    delete:
      operationId: deleteAppServiceAccountToken
      parameters:
      - explode: false
        in: path
        name: tokenId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Delete App Service Account Token
      tags:
      - app-service-account-tokens
      x-doc-tags:
      - App Service Accounts
    get:
      operationId: getAppServiceAccountToken
      parameters:
      - explode: false
        in: path
        name: tokenId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppUserAccessTokenViewResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Get App Service Account Token
      tags:
      - app-service-account-tokens
      x-doc-tags:
      - App Service Accounts
    patch:
      operationId: updateAppServiceAccountToken
      parameters:
      - explode: false
        in: path
        name: tokenId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppUserAccessTokenUpdateRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppUserAccessTokenViewResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Update App Service Account Token
      tags:
      - app-service-account-tokens
      x-doc-tags:
      - App Service Accounts
components:
  schemas:
    AppUserAccessTokenUpdateRequest:
      example:
        expires: 2000-01-23 04:56:07+00:00
        never_expires: true
        name: name
      properties:
        expires:
          format: date-time
          type: string
        name:
          type: string
        never_expires:
          type: boolean
      type: object
    AppUserAccessTokenViewResponse:
      example:
        expires: expires
        created: 2000-01-23 04:56:07+00:00
        name: name
        id: id
        last_active: last_active
      properties:
        created:
          format: date-time
          type: string
        expires:
          type:
          - string
          - 'null'
        id:
          type: string
        last_active:
          type:
          - string
          - 'null'
        name:
          type: string
      required:
      - created
      - id
      - name
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: Personal Access Token
      scheme: bearer
      type: http
    sessionAuth:
      in: cookie
      name: control_plane_session
      type: apiKey
