openapi: 3.2.0
info:
  description: API for Synadia Control Plane / Synadia Cloud
  title: Synadia Control Plane / Synadia Cloud Auth Callout API
  version: beta
servers:
- description: Path to Synadia Control Plane Server Api
  url: '{baseUrl}/api'
  variables:
    baseUrl:
      default: ''
security:
- bearerAuth: []
  sessionAuth: []
tags:
- name: auth-callout
paths:
  /core/beta/auth-callout/{authCalloutId}:
    delete:
      description: Remove auth callout config and update the control account jwt
      operationId: deleteAuthCallout
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Delete Auth Callout Config
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
    get:
      description: Returns the Auth Callout Config
      operationId: getAuthCallout
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCalloutViewResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Auth Callout Config
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
  /core/beta/auth-callout/{authCalloutId}/target-accounts:
    get:
      description: Get a list of configured Target Accounts
      operationId: listAuthCalloutTargetAccounts
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCalloutTargetAccountListResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Get Target Account List
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
    post:
      description: Configure a target account
      operationId: addAuthCalloutTargetAccount
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCalloutAddTargetAccountRequest'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Configure Target Account
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
  /core/beta/auth-callout/{authCalloutId}/target-accounts/{targetAccountId}:
    delete:
      description: Remove configured target account entry
      operationId: deleteAuthCalloutTargetAccount
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: targetAccountId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Delete Target Account
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
  /core/beta/auth-callout/{authCalloutId}/users:
    get:
      description: Get a list of configured Target Accounts
      operationId: listAuthCalloutUsers
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCalloutUsersListResponse'
          description: Success
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Get Target Account List
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
    post:
      description: Create a Control Account User that can access auth callout
      operationId: addAuthCalloutUser
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCalloutAddUserRequest'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Create Auth Callout User
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
  /core/beta/auth-callout/{authCalloutId}/users/{acUserId}:
    delete:
      description: Remove control account auth callout user
      operationId: deleteAuthCalloutUser
      parameters:
      - explode: false
        in: path
        name: authCalloutId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: acUserId
        required: true
        schema:
          type: string
        style: simple
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      summary: Delete Control Account User
      tags:
      - auth-callout
      x-doc-tags:
      - Auth Callout
components:
  schemas:
    AuthCalloutTargetAccountListResponse:
      example:
        items:
        - target_account_name: target_account_name
          control_account_sk_group_id: control_account_sk_group_id
          target_account_id: target_account_id
          control_account_sk_group_name: control_account_sk_group_name
          target_account_sk_group_id: target_account_sk_group_id
          id: id
          target_account_sk_group_name: target_account_sk_group_name
        - target_account_name: target_account_name
          control_account_sk_group_id: control_account_sk_group_id
          target_account_id: target_account_id
          control_account_sk_group_name: control_account_sk_group_name
          target_account_sk_group_id: target_account_sk_group_id
          id: id
          target_account_sk_group_name: target_account_sk_group_name
      properties:
        items:
          items:
            $ref: '#/components/schemas/AuthCalloutTargetAccountViewResponse'
          type: array
      required:
      - items
      type: object
    AuthCalloutAuthenticatorConfigViewResponse:
      example:
        id: id
        type: type
        config: config
        enabled: true
      properties:
        config:
          type: string
        enabled:
          type: boolean
        id:
          type: string
        type:
          type: string
      required:
      - config
      - enabled
      - id
      - type
      type: object
    AuthCalloutTargetAccountViewResponse:
      example:
        target_account_name: target_account_name
        control_account_sk_group_id: control_account_sk_group_id
        target_account_id: target_account_id
        control_account_sk_group_name: control_account_sk_group_name
        target_account_sk_group_id: target_account_sk_group_id
        id: id
        target_account_sk_group_name: target_account_sk_group_name
      properties:
        control_account_sk_group_id:
          type: string
        control_account_sk_group_name:
          type: string
        id:
          type: string
        target_account_id:
          type: string
        target_account_name:
          type: string
        target_account_sk_group_id:
          type: string
        target_account_sk_group_name:
          type: string
      required:
      - control_account_sk_group_id
      - control_account_sk_group_name
      - id
      - target_account_id
      - target_account_name
      - target_account_sk_group_id
      - target_account_sk_group_name
      type: object
    AuthCalloutUserViewResponse:
      example:
        name: name
        id: id
        nats_user_id: nats_user_id
      properties:
        id:
          type: string
        name:
          type: string
        nats_user_id:
          type: string
      required:
      - id
      - name
      - nats_user_id
      type: object
    AuthCalloutConfig:
      example:
        xkey_public: xkey_public
        control_account_id: control_account_id
        system_id: system_id
        id: id
      properties:
        control_account_id:
          type: string
        id:
          type: string
        system_id:
          type: string
        xkey_public:
          type: string
      required:
      - control_account_id
      - id
      - system_id
      type: object
    AuthCalloutUsersListResponse:
      example:
        items:
        - name: name
          id: id
          nats_user_id: nats_user_id
        - name: name
          id: id
          nats_user_id: nats_user_id
      properties:
        items:
          items:
            $ref: '#/components/schemas/AuthCalloutUserViewResponse'
          type: array
      required:
      - items
      type: object
    AuthCalloutAddUserRequest:
      example:
        nats_user_id: nats_user_id
      properties:
        nats_user_id:
          type: string
      required:
      - nats_user_id
      type: object
    AuthCalloutViewResponse:
      allOf:
      - $ref: '#/components/schemas/AuthCalloutConfig'
      example:
        authenticators:
        - id: id
          type: type
          config: config
          enabled: true
        - id: id
          type: type
          config: config
          enabled: true
        target_accounts:
        - target_account_name: target_account_name
          control_account_sk_group_id: control_account_sk_group_id
          target_account_id: target_account_id
          control_account_sk_group_name: control_account_sk_group_name
          target_account_sk_group_id: target_account_sk_group_id
          id: id
          target_account_sk_group_name: target_account_sk_group_name
        - target_account_name: target_account_name
          control_account_sk_group_id: control_account_sk_group_id
          target_account_id: target_account_id
          control_account_sk_group_name: control_account_sk_group_name
          target_account_sk_group_id: target_account_sk_group_id
          id: id
          target_account_sk_group_name: target_account_sk_group_name
        users:
        - name: name
          id: id
          nats_user_id: nats_user_id
        - name: name
          id: id
          nats_user_id: nats_user_id
      properties:
        authenticators:
          items:
            $ref: '#/components/schemas/AuthCalloutAuthenticatorConfigViewResponse'
          type: array
        target_accounts:
          items:
            $ref: '#/components/schemas/AuthCalloutTargetAccountViewResponse'
          type: array
        users:
          items:
            $ref: '#/components/schemas/AuthCalloutUserViewResponse'
          type: array
      type: object
    AuthCalloutAddTargetAccountRequest:
      example:
        sk_group_id: sk_group_id
        account_id: account_id
        control_account_sk_group_id: control_account_sk_group_id
      properties:
        account_id:
          type: string
        control_account_sk_group_id:
          type: string
        sk_group_id:
          type: string
      required:
      - account_id
      - control_account_sk_group_id
      - sk_group_id
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: Personal Access Token
      scheme: bearer
      type: http
    sessionAuth:
      in: cookie
      name: control_plane_session
      type: apiKey
